sudo: false

language: cpp

compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
    - libgtest-dev
    - qt4-dev-tools

before_script:
 - mkdir build
 - cd build
 - cmake -DOPENMESH_BUILD_PYTHON_BINDINGS=OFF -DOPENMESH_BUILD_UNIT_TESTS=ON ../OpenMesh

script: make && make test

