sudo: false

language: cpp

compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
    - libgtest-dev
    - qt4-dev-tools

before_script:
 - mkdir gtest
 - cd gtest
 - cmake /usr/src/gtest
 - make
 - mkdir lib
 - mv *.a lib
 - mkdir include
 - cp -r /usr/include/gtest include
 - cd ..
 - mkdir build
 - cd build
 - cmake -DOPENMESH_BUILD_PYTHON_BINDINGS=OFF -DOPENMESH_BUILD_UNIT_TESTS=ON -DGTEST_PREFIX=${TRAVIS_BUILD_DIR}/gtest ../OpenMesh

script: make && make test

